name: "CI"
on:
  push:
    branches:
      - 'build/*'
  pull_request:
    branches:
      - 'dev'
      - 'main'

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: Goalkeeper-2

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup test environment # requires importing assets
        run: |
          godot --headless --import
      - name: Run tests
        run: |
          godot -s addons/gut/gut_cmdln.gd -gdir=res://test/unit -gexit --headless
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p builds/linux
          godot --headless --verbose --export-release "Linux" builds/linux/$(EXPORT_NAME).x86_64
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: builds/
          if-no-files-found: error
